<?php

use Illuminate\Database\Seeder;

class BackstoryTraitSeeder extends Seeder
{
    private $traits = [
        "doesn't believe in magic, ever",
        "hates wearing their glasses",
        "finds it impossible to speak to girls",
        "has always wanted to open their own tavern",
        "has a huge debt to pay back",
        "suffers from claustrophobia",
        "is really (I MEAN REALLY) afraid of the dark",
        "makes inappropriate jokes at the worst times",
        "is afraid of heights",
        "doesn't understand the concept of politeness",
        "always alliterates their anecdotes",
        "has a bad gambling problem",
        "was told they'll never be good enough",
        "wants everyone to like them",
        "never takes their armour off, just in case",
        "always needs to be the centre of attention",
        "was left out of their father's will",
        "is writing an autobiography",
        "has serious daddy issues",
        "has a drinking problem",
        "is completely colour blind",
        "gets nervous speaking in front of crowds",
        "is afraid of sharp edges",
        "suffers from nosebleeds",
        "is uncomfortable around old people (they smell like death)",
        "can't swim",
        "was brought up to be a librarian",
        "grew up in a graveyard",
        "is afraid of fire",
        "hates music",
        "grew up fat",
        "distrusts all authority",
        "mistrusts anyone smaller than them",
        "is afraid of dogs",
        "was once rescued by wolves",
        "has anger problems",
        "always romanticised adventure",
        "can't read",
        "deserted the army",
        "is responsible for their sister's death",
        "is certain their days are numbered",
        "always takes first watch",
        "can't silence the voices",
        "meditates before dawn",
        "constantly watches their back",
        "always refers to inanimate objects as 'she'",
        "always wakes up on the right side of the bed",
        "always keeps their promises",
        "wants to be famous, no matter what",
        "believes trees can speak to them and them alone",
        "is trying to get out of the gladiator business to settle down",
        "takes great delight in identifying new beetle species",
        "has serious body image problems",
        "is a recovering gambling addict",
        "secretly became an gladiator to impress a love interest",
        "is afraid a gang will kill them if they try to leave",
        "searches endlessly for their kidnapped child",
        "would rather kill you than make eye contact",
        "was kidnapped by cultists",
        "has twenty-seven siblings to provide for",
        "is searching for the perfect culinary dish",
        "has nothing left to lose",
        "doesn't know their own strength",
        "has had it up to here with everyone's crap",
        "is red-green colorblind",
        "carries the skull of their best friend",
        "has a serious weapons fetish",
        "has taken a vow of silence",
        "is just trying to get by",
        "has really bad hay fever",
        "wants to clear their name",
        "doesn't believe in hygiene",
        "is being hunted by a terrible monster",
        "once survived a boiling cauldron",
        "forever picking fights to 'win back honour'",
        "can't stand silence",
        "lost minor appendages due to their gambling addiction",
        "is absolutely astonished by jugglers",
        "can't sleep indoors",
        "only sleeps with the lights on",
        "hates to be clean",
        "drunkenly swore a blood oath and forgot what for",
        "doesn't perceive gender",
        "realised the importance of literacy far too late in life",
        "bangs on about their genealogy to everyone",
        "keeps a blacklist",
        "gets easily attached to people",
        "has cheated death more times than they deserved",
        "finds armour too restricting",
        "has no sense of smell",
        "refuses to bathe",
        "loved, lost and never loved again",
        "is lactose intolerant",
        "adds a notch to their sword every night",
        "prefers to fight drunk",
        "thinks they can read the future, but consistently gets it wrong",
        "killed their brother in a duel over their inheritance",
        "speaks in sentences of exactly ten words",
        "was raised as a hostage by their father's enemies",
        "moonlights as a private investigator",
        "has an irrational fear of cats",
        "is completely and utterly tone-deaf",
        "is running from a marriage arranged by their parents",
        "wants to prove they're no longer that goofy kid",
        "has gotten away with murder",
        "knows seven dangerous secrets",
        "has a debilitating fear of wide open spaces",
        "always speaks in the third person",
        "is manically obsessed with etiquette",
        "is secretly fond of embroidery",
        "is searching for a rare fertility herb",
        "is a compulsive liar",
        "hates the written word",
        "wants to one day own their own ship ",
        "likes to settle arguments with headbutting contests",
        "is pretty tight-fisted with their gold",
        "was disowned by their family",
        "names every piece of their gear",
        "is a complete exhibitionist",
        "always thinks outside the box",
        "carries a cryptic treasure map they won in a tavern bet",
        "has been exiled twice under different names",
        "constantly places themselves in danger, just to prove a point",
        "seeks to end a family feud",
        "has a pretty selective memory",
        "has accepted death as an inevitability",
        "has been on the run for over three years",
        "is terrified of rats",
        "was forced to watch their families execution",
        "can't stand children",
        "worries some of their memories have been tampered with",
        "hates to be touched",
        "lost their sense of smell in a bar fight",
        "likes to speak in rhyme",
        "can't seem to hold their liquor",
        "unwittingly misuses words all the bloody time",
        "has some pretty shady connections",
        "was beaten and imprisoned for their religious beliefs",
        "started a rebellion in the northern mountains",
        "acts shallow but only to hide their insecurities",
        "makes all minor decisions by flipping a coin",
        "wants to become a famous singer",
        "always looks their best",
        "is haunted by the ghost of their father",
        "was exiled by their brother the king",
        "always gives the good news first",
        "used to work as a tavern bouncer",
        "tries to be a friend to everyone",
        "hates riding horses",
        "left their home in disgrace",
        "doesn't understand sarcasm",
        "suffers from night terrors",
        "never passes up a chance to say, 'I told you so.'",
        "was framed for the murder of a famous and well-loved innkeeper",
        "believes in racial purity",
        "is a former bare knuckle brawler",
        "always cuts to the chase",
        "always gives the bad news first",
        "was a weapons instructor for the Legio",
        "is on the run after having an affair with a patrician's daughter",
        "has a twin that constantly impersonates them",
        "hasn't been quite right since the accident",
        "hasn't accomplished anything in their short life yet",
        "lost their marbles a long time ago",
        "has a burning hatred for pirates",
        "aims to learn every language in the land",
        "owes money to the wrong people",
        "believes in an eye for an eye",
        "never turns the other cheek",
        "once served as a court jester",
        "in hindsight shouldn't have had the treasure map tattooed on themselves",
        "already made and lost a fortune",
        "has a poem for all occasions",
        "was drafted into the army at fourteen",
        "has a regular sleepwalking issue",
        "was cut from their dead mother's womb",
        "was jailed for a crime they didn't commit",
        "is posing as someone else",
        "was expelled from the royal guards",
        "has never been kissed",
        "suffers from crippling stage-fright",
        "is writing an epic poem about their adventures",
        "really knows how to party",
        "loves to haggle",
        "suffers from a recurring nightmare",
        "needs to earn the trust of a hated patrician",
        "came out of retirement for this adventure",
        "loots every kill but leaves enough to pay for their burial",
        "woke up in a bar with no memory and a sealed letter",
        "is haunted by the ghosts of their forefathers",
        "doesn't have time for all this prophecy bullshit",
        "is dealing with a midlife crisis",
        "has delusions of grandeur",
        "just wants their money back",
        "always wanted to be an artist",
        "believes armour is just a sign of being posh and over privileged",
        "likes to settle arguments with an arm wrestle",
        "never returned anything they borrowed",
        "had their nose cut off in a duel",
        "bribed a nobleman to help them smuggle slaves out of a tyrannical kingdom",
        "suffers from vertigo",
        "lost two fingers in a training accident",
        "is tracking down the treasure their father died trying to find",
        "is getting too old for all this",
        "no longer dreams",
        "rejected a foreign prince's marriage proposal",
        "has a bad habit of making 'funny' quips after every kill",
        "ran away at the age of eleven",
        "carries the scars of an attempted suicide",
        "won a duel they were supposed to lose out of sheer luck",
        "hates being made to wait",
        "seems to know everyone",
        "keeps getting mistaken for a famous gladiator",
        "lost their best friend in an ambush",
        "is haunted by the ghosts of those they kill",
        "was written out of their family will",
        "is planning to retire next year",
        "is in way too deep with the wrong sort of people",
        "exaggerates everything they talk about",
        "has no concept of personal space",
        "never got the proper training",
        "is in so far over their head that they can't help but laugh",
        "can only whisper after an attempted hanging",
        "is really good at bribing officials",
        "is quick to take credit and assign blame",
        "refuses to admit they're past their prime",
        "has never had their hair cut",
        "only became an adventurer after losing a bet",
        "is wanted for a reward",
        "wears a mysterious necklace that constantly brings them out in a rash",
        "parties hard, way too hard.",
        "is convinced they're always being left out",
        "doesn't speak a word of common",
    ];

    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        collect($this->traits)->each(function (string $trait) {
            \App\Models\BackstoryTrait::create([
                'text' => $trait,
            ]);
        });
    }
}
